/* BDL PLAYER ACCOUNTS + RECOVERY */
const AMY_TEST_PLAYER_ID="a06f21c0-62a7-4072-bad8-e12f6d846e99";
const DRBDL_TEST_PLAYER_ID="7918f225-6787-46ba-bc07-fbbda246448f";
const LEGACY_BDL_FANS_PLAYER_ID="1dc098f2-7682-4cff-b3cd-9e92d79c3fb5";
function normalizePlayerName(v){return String(v||"").normalize("NFKC").trim().replace(/\s+/g," ").toLowerCase()}
function isAmyTestIdentity(){return String(playerId())===AMY_TEST_PLAYER_ID&&normalizePlayerName(playerName())==="amy.test"}
function isDrBDLTestIdentity(){return String(playerId())===DRBDL_TEST_PLAYER_ID&&normalizePlayerName(playerName())==="drbdl.test"}
function isTestIdentity(){return isAmyTestIdentity()||isDrBDLTestIdentity()}
function needsReservedNameChange(){return String(playerId())===LEGACY_BDL_FANS_PLAYER_ID&&normalizePlayerName(playerName()).includes("bdl")}
async function accountApi(body){const r=await fetch(QUIZ_SERVICE,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||"Something went wrong.");e.status=r.status;e.data=d;throw e}return d}
function clearLocalIdentity(){localStorage.removeItem("bdlPlayerName");localStorage.removeItem("bdlPlayerId")}
function generatePlayerId(){return crypto.randomUUID?crypto.randomUUID():"bdl-"+Date.now()+"-"+Math.random().toString(36).slice(2)}
function showAccountChoice(){document.getElementById("mainHeader").style.display="none";page(`<div class="center"><h1>Quiz Me This<br>BDL<br>Quiz Me That</h1><p>Choose how you want to continue.</p><button onclick="showNewPlayerRegistration()">NEW PLAYER</button><button onclick="showAccountRecovery()">I ALREADY HAVE AN ACCOUNT</button></div>`)}
function showNewPlayerRegistration(){page(`<div class="center"><h2>NEW PLAYER</h2><p>Choose your unique player name.</p><input id="newPlayerName" placeholder="Your player name" maxlength="50"><div id="accountMessage" class="notice" style="display:none"></div><button id="registerPlayerButton" onclick="registerNewPlayer()">CREATE ACCOUNT</button>${back("showAccountChoice")}</div>`)}
async function registerNewPlayer(){const i=document.getElementById("newPlayerName"),b=document.getElementById("registerPlayerButton"),m=document.getElementById("accountMessage"),name=String(i?.value||"").trim();if(!name){i?.focus();return}b.disabled=true;b.textContent="CREATING...";const id=generatePlayerId();try{const d=await accountApi({action:"register_player",player_id:id,player_name:name});localStorage.setItem("bdlPlayerId",d.player_id||id);localStorage.setItem("bdlPlayerName",d.player_name||name);dashboardCache=null;migrateLegacyAnswers();d.recovery_code?showRecoveryCodeOnce(d.recovery_code):showStartScreen()}catch(e){m.style.display="block";m.textContent=e.status===409&&String(e.message).includes("reserved_bdl_name")?"BDL is reserved and cannot be used in regular player names. Please choose another name.":e.status===409&&String(e.message).includes("name_taken")?"That player name is already in use. Please choose another name.":e.message||"Your account could not be created.";b.disabled=false;b.textContent="CREATE ACCOUNT"}}
function showReservedNameChange(){document.getElementById("mainHeader").style.display="none";page(`<div class="section settings"><h2 class="center">CHOOSE A NEW PLAYER NAME</h2><div class="settings-card center"><p><strong>BDL</strong> is now reserved and can no longer be used in regular player names.</p><p>Please choose a new unique player name to continue.</p><input id="reservedNewPlayerName" placeholder="Your new player name" maxlength="50"><div id="reservedNameMessage" class="notice" style="display:none"></div><button id="reservedNameButton" class="settings-button" onclick="saveReservedNameChange()">SAVE NEW NAME</button></div></div>`)}
async function saveReservedNameChange(){const i=document.getElementById("reservedNewPlayerName"),b=document.getElementById("reservedNameButton"),m=document.getElementById("reservedNameMessage"),name=String(i?.value||"").trim();if(!name){i?.focus();return}b.disabled=true;b.textContent="SAVING...";try{const d=await accountApi({action:"rename_player",player_id:playerId(),new_player_name:name});localStorage.setItem("bdlPlayerName",d.player_name||name);dashboardCache=null;showStartScreen()}catch(e){m.style.display="block";m.textContent=String(e.message).includes("reserved_bdl_name")?"BDL is reserved. Please choose a name without BDL.":String(e.message).includes("name_taken")?"That player name is already in use. Please choose another name.":"Your player name could not be changed.";b.disabled=false;b.textContent="SAVE NEW NAME"}}
function showRecoveryCodeOnce(code){page(`<div class="section settings"><h2 class="center">YOUR RECOVERY CODE</h2><div class="settings-card center"><p>Keep this code somewhere safe. You need it if you change device.</p><div class="notice" style="font-size:22px;font-weight:bold;letter-spacing:1px">${html(code)}</div><p>This code is shown only now. You can generate a new one later in Personal Settings.</p><button class="settings-button" onclick="confirmRecoveryCodeSaved()">I HAVE SAVED MY CODE</button></div></div>`)}
function confirmRecoveryCodeSaved(){showStartScreen()}
function showAccountRecovery(){clearLocalIdentity();page(`<div class="center"><h2>RECOVER ACCOUNT</h2><p>Enter your player name and recovery code.</p><input id="recoverPlayerName" placeholder="Player name" maxlength="50"><input id="recoverPlayerCode" placeholder="BDL-XXXX-XXXX-XXXX-XXXX" maxlength="24" autocapitalize="characters"><div id="recoveryMessage" class="notice" style="display:none"></div><button id="recoverPlayerButton" onclick="recoverExistingPlayer()">RECOVER ACCOUNT</button>${back("showAccountChoice")}</div>`)}
async function recoverExistingPlayer(){const name=String(document.getElementById("recoverPlayerName")?.value||"").trim(),code=String(document.getElementById("recoverPlayerCode")?.value||"").trim(),b=document.getElementById("recoverPlayerButton"),m=document.getElementById("recoveryMessage");if(!name||!code){m.style.display="block";m.textContent="Enter both your player name and recovery code.";return}b.disabled=true;b.textContent="CHECKING...";try{const d=await accountApi({action:"recover_player",player_name:name,recovery_code:code});localStorage.setItem("bdlPlayerId",d.player_id);localStorage.setItem("bdlPlayerName",d.player_name);dashboardCache=null;migrateLegacyAnswers();showStartScreen()}catch(e){m.style.display="block";m.textContent=e.status===401?"The player name or recovery code is not correct.":e.status===409?"No recovery code has been created for this account yet.":"Your account could not be recovered.";b.disabled=false;b.textContent="RECOVER ACCOUNT"}}
answerKey=function(index){return "bdlQuizAnswer_"+playerId()+"_"+questionNumber(index)};function legacyAnswerKey(index){return "bdlQuizAnswer_"+questionNumber(index)}
function migrateLegacyAnswers(){const id=localStorage.getItem("bdlPlayerId");if(!id)return;for(let i=0;i<questions.length;i++){const old=legacyAnswerKey(i),key="bdlQuizAnswer_"+id+"_"+questionNumber(i);if(localStorage.getItem(key)===null){const v=localStorage.getItem(old);if(v!==null)localStorage.setItem(key,v)}}}
showStartScreen=function(){document.getElementById("mainHeader").style.display="none";const day=quizDay();if(day<0){page(`<div class="center"><h1>Quiz Me This<br>BDL<br>Quiz Me That</h1><p>The Daily Quiz starts on 11 August at 08:00.</p></div>`);return}if(day>=questions.length){page(`<div class="center"><h1>Quiz Me This<br>BDL<br>Quiz Me That</h1><p>No new Daily Quiz is scheduled yet.</p></div>`);return}const name=playerName(),id=localStorage.getItem("bdlPlayerId");if(!name||!id){showAccountChoice();return}if(needsReservedNameChange()){showReservedNameChange();return}migrateLegacyAnswers();page(`<div class="center"><h1>Quiz Me This<br>BDL<br>Quiz Me That</h1><p>Welcome back, <strong>${html(name)}</strong>!</p><button class="center" onclick="startQuiz()">START QUIZ</button></div>`)};
showMainMenu=function(){document.getElementById("mainHeader").style.display="block";const t=isTestIdentity()?`<button onclick="showTestMode()">TEST MODE</button>`:"";page(`<h2 class="center">Welcome, ${html(playerName())}</h2><div class="menu main-menu"><button onclick="showMyStatistics()">MY STATISTICS</button><button onclick="showQuizMenu()">QUIZ</button><button onclick="showHistory()">HISTORY</button><button onclick="showPersonalSettings()">PERSONAL SETTINGS</button>${t}</div>`)};
function showTestMode(){if(!isTestIdentity()){showMainMenu();return}page(`<div class="section settings"><h2 class="center">TEST MODE</h2><div class="settings-card center"><p>${html(playerName())} is recognised as a test account.</p></div></div>${back("showMainMenu")}`)}
showPersonalSettings=async function(){const name=playerName();page(`<div class="section settings"><h2 class="center">PERSONAL SETTINGS</h2><div class="settings-card"><h3>Ranking privacy</h3><p>Choose whether your player name and quiz statistics may appear in the rankings.</p><p id="rankingPrivacyStatus">Checking preference...</p><button id="rankingPrivacyButton" class="settings-button" onclick="toggleRankingPrivacy()" disabled>PLEASE WAIT...</button></div><div class="settings-card" style="margin-top:14px"><h3>Account recovery</h3><p>Reconnect this app to your existing player account with your recovery code.</p><input id="settingsRecoveryName" value="${html(name)}" placeholder="Player name" maxlength="50"><input id="settingsRecoveryCode" placeholder="BDL-XXXX-XXXX-XXXX-XXXX" maxlength="24" autocapitalize="characters" autocomplete="off"><div id="settingsRecoveryMessage" class="notice" style="display:none"></div><button id="settingsRecoverButton" class="settings-button" onclick="recoverFromPersonalSettings()">RECOVER THIS ACCOUNT</button><p id="recoveryStatus" style="margin-top:16px">Checking current connection...</p><button id="recoveryButton" class="settings-button" onclick="createOrRotateRecoveryCode()" disabled>PLEASE WAIT...</button></div><div class="settings-card" style="margin-top:14px"><h3>Push notifications</h3><p>Receive a notification when the new Daily Quiz is available.</p><p id="pushStatus">Checking status...</p><button id="pushButton" class="settings-button" onclick="togglePushNotifications()">PLEASE WAIT...</button></div></div>${back("showMainMenu")}`);await Promise.all([refreshRankingPrivacy(),refreshRecoveryStatus(),refreshPushStatus()])};
let currentRankingPrivacy=false;async function refreshRankingPrivacy(){const s=document.getElementById("rankingPrivacyStatus"),b=document.getElementById("rankingPrivacyButton");if(!s||!b)return;try{const d=await accountApi({action:"ranking_preference",player_id:playerId()});currentRankingPrivacy=d.share_ranking===true;s.innerHTML=d.decided?(currentRankingPrivacy?"<strong>VISIBLE</strong> — You appear in rankings.":"<strong>PRIVATE</strong> — You do not appear in rankings."):"<strong>NOT CHOSEN YET</strong> — Your results remain private.";b.textContent=currentRankingPrivacy?"KEEP MY RESULTS PRIVATE":"INCLUDE ME IN RANKINGS";b.disabled=false}catch(e){s.textContent="Ranking preference could not be checked.";b.textContent="TRY AGAIN";b.disabled=false}}async function toggleRankingPrivacy(){const b=document.getElementById("rankingPrivacyButton");if(b)b.disabled=true;try{await accountApi({action:"set_ranking_preference",player_id:playerId(),player_name:playerName(),share_ranking:!currentRankingPrivacy});dashboardCache=null;await refreshRankingPrivacy()}catch(e){alert("Your ranking preference could not be changed.");if(b)b.disabled=false}}
async function recoverFromPersonalSettings(){const name=String(document.getElementById("settingsRecoveryName")?.value||"").trim(),code=String(document.getElementById("settingsRecoveryCode")?.value||"").trim(),b=document.getElementById("settingsRecoverButton"),m=document.getElementById("settingsRecoveryMessage");m.style.display="none";if(!name||!code){m.textContent="Enter your player name and recovery code.";m.style.display="block";return}b.disabled=true;b.textContent="CHECKING...";try{const d=await accountApi({action:"recover_player",player_name:name,recovery_code:code});localStorage.setItem("bdlPlayerId",d.player_id);localStorage.setItem("bdlPlayerName",d.player_name);dashboardCache=null;migrateLegacyAnswers();m.textContent="Account recovered successfully.";m.style.display="block";setTimeout(()=>showStartScreen(),600)}catch(e){m.textContent=e.status===401?"The player name or recovery code is not correct.":e.status===409?"No recovery code has been created for this account yet.":"Your account could not be recovered. Please try again.";m.style.display="block";b.disabled=false;b.textContent="RECOVER THIS ACCOUNT"}}
async function refreshRecoveryStatus(){const s=document.getElementById("recoveryStatus"),b=document.getElementById("recoveryButton");if(!s||!b)return;try{const d=await accountApi({action:"recovery_status",player_id:playerId(),player_name:playerName()});s.innerHTML=d.recovery_enabled?"<strong>Status: SET</strong>":"<strong>Status: NOT SET</strong>";b.textContent=d.recovery_enabled?"GENERATE NEW RECOVERY CODE":"CREATE RECOVERY CODE";b.disabled=false}catch(e){if(e.status===403){s.textContent="This app is not connected to this player account yet. Enter your recovery code above.";b.style.display="none"}else{s.textContent="Recovery status could not be checked.";b.textContent="TRY AGAIN";b.disabled=false}}}async function createOrRotateRecoveryCode(){const b=document.getElementById("recoveryButton");if(b){b.disabled=true;b.textContent="GENERATING..."}try{const s=await accountApi({action:"recovery_status",player_id:playerId(),player_name:playerName()});const d=s.recovery_enabled?await accountApi({action:"rotate_recovery_code",player_id:playerId(),player_name:playerName()}):await accountApi({action:"register_player",player_id:playerId(),player_name:playerName()});if(!d.recovery_code)throw new Error("No recovery code was returned.");showRecoveryCodeOnce(d.recovery_code)}catch(e){alert("A recovery code could not be generated. Reconnect your account first.");await refreshRecoveryStatus()}}
submitAnswer=async function(){const index=quizDay(),q=questions[index];if(selectedAnswer===null||!q)return;const b=document.getElementById("submitButton");if(b){b.disabled=true;b.textContent="SUBMITTING..."}try{const r=await fetch(QUIZ_SERVICE,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"submit_answer",player_id:playerId(),player_name:playerName(),quiz_date:dateString(effectiveDate()),question_num:questionNumber(index),answer:String.fromCharCode(65+selectedAnswer),is_correct:selectedAnswer===q.correct})});const d=await r.json().catch(()=>({}));if(r.ok){storeAnswer(index,selectedAnswer);dashboardCache=null;showThankYouPage();return}if(r.status===409&&String(d.error||"").includes("reserved_bdl_name")){showReservedNameChange();return}if(r.status===409&&String(d.error||"").includes("name_taken"))throw new Error("This app is not connected to this player account yet. Go to Personal Settings and enter your recovery code.");throw new Error(d.error||"Your answer could not be submitted.")}catch(e){if(b){b.disabled=false;b.textContent="SUBMIT ANSWER"}alert(e.message||"Your answer could not be submitted.")}};

const baseShowMyStatistics=showMyStatistics;
showMyStatistics=async function(){
  await baseShowMyStatistics();
  const stats=document.querySelector(".section.stats");
  const grid=stats?.querySelector(".stat-grid");
  if(!stats||!grid||document.getElementById("statsUpdateNote"))return;
  const note=document.createElement("div");
  note.id="statsUpdateNote";
  note.className="notice";
  note.innerHTML="<strong>Played</strong> updates immediately after you submit an answer. <strong>Correct, Incorrect and Accuracy</strong> are updated the following quiz day, when the correct answer is revealed.";
  grid.insertAdjacentElement("afterend",note);
};

migrateLegacyAnswers();showStartScreen();