/* BDL bootstrap — local-first startup. The legacy shell is used only once as migration fallback. */
(function(){
  const MIGRATION_SOURCE='https://raw.githubusercontent.com/BDL-Amy/Quiz-Me-This-BDL-Quiz-Me-That/18a31bcbb2c83c1dbc405b3b1d23bd0492b23567/index.html';
  const VERSION='20260917-result2';
  const CACHE_KEY='bdl_app_shell_v2';
  function modernize(html){let out=html.replace('<script src="questions-51-60.js?v=20260916-live2"></script>','').replace('<script src="quiz-schedule-1530.js?v=20260917a"></script>','').replace(/questions-51-60\.js\?v=[^"']+/g,`questions-51-60.js?v=${VERSION}`).replace(/quiz-schedule-1530\.js\?v=[^"']+/g,`quiz-schedule-1530.js?v=${VERSION}`).replace(/result-catchphrases\.js\?v=[^"']+/g,`result-catchphrases.js?v=${VERSION}`).replace(/account\.js\?v=[^"']+/g,`account.js?v=${VERSION}`).replace(/history\.js\?v=[^"']+/g,`history.js?v=${VERSION}`).replace(/test-platform\.js\?v=[^"']+/g,`test-platform.js?v=${VERSION}`).replace(/recovery-onboarding\.js\?v=[^"']+/g,`recovery-onboarding.js?v=${VERSION}`).replace(/results-menu\.js\?v=[^"']+/g,`results-menu.js?v=${VERSION}`).replace(/performance\.js\?v=[^"']+/g,`performance.js?v=${VERSION}`);if(!out.includes('performance.js'))out=out.replace('</body>',`<script src="performance.js?v=${VERSION}"></script></body>`);return out}
  function launch(shell){document.open();document.write(shell);document.close()}
  let local='';try{local=localStorage.getItem(CACHE_KEY)||localStorage.getItem('bdl_legacy_shell_v1')||''}catch(e){}
  if(local){const shell=modernize(local);try{localStorage.setItem(CACHE_KEY,shell);localStorage.removeItem('bdl_legacy_shell_v1')}catch(e){}launch(shell);return}
  fetch(MIGRATION_SOURCE,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('migration_source_unavailable');return r.text()}).then(t=>{const shell=modernize(t);try{localStorage.setItem(CACHE_KEY,shell)}catch(e){}launch(shell)}).catch(()=>{const el=document.getElementById('restore');if(el)el.textContent='The quiz could not be loaded. Please refresh.'});
})();