/* BDL HISTORY + RANKINGS */
function historyDateForIndex(index){const d=new Date(2026,7,11);d.setDate(d.getDate()+index);return d}
function historyDateLabel(d){return d.toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
function historyShortDate(d){return d.toLocaleDateString("en-GB",{day:"numeric",month:"short"}).toUpperCase()}
function historyMonday(d){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());const day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x}
function historyAddDays(d,n){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());x.setDate(x.getDate()+n);return x}
function historyReleasedLastIndex(){return Math.min(questions.length-1,quizDay()-1)}
showHistory=function(){page(`<div class="section history"><h2 class="center">HISTORY</h2><div class="menu"><button onclick="showPreviousQuestions()" style="border-color:var(--history);font-weight:bold">PREVIOUS QUESTIONS</button><button onclick="showRankings()" style="border-color:var(--gold);font-weight:bold">RANKINGS</button><button onclick="showWallOfFameMenu()" style="border-color:var(--history);font-weight:bold">WALL OF FAME</button></div></div>${back("showMainMenu")}`)};
function showPreviousQuestions(){const last=historyReleasedLastIndex();if(last<0){page(`<div class="section history"><h2 class="center">PREVIOUS QUESTIONS</h2><div class="notice">No previous questions are available yet.</div></div>${back("showHistory")}`);return}const weeks=new Map();for(let i=0;i<=last;i++){const d=historyDateForIndex(i),m=historyMonday(d),key=dateString(m);if(!weeks.has(key))weeks.set(key,{monday:m,indices:[]});weeks.get(key).indices.push(i)}const buttons=[...weeks.values()].sort((a,b)=>b.monday-a.monday).map(w=>`<button onclick="showPreviousQuestionsWeek('${dateString(w.monday)}')" style="border-color:var(--history);font-weight:bold">${historyShortDate(w.monday)} – ${historyShortDate(historyAddDays(w.monday,6))}</button>`).join("");page(`<div class="section history"><h2 class="center">PREVIOUS QUESTIONS</h2><p class="center">Choose a quiz week.</p><div class="menu">${buttons}</div></div>${back("showHistory")}`)}
async function historyPlayerAnswer(index){let selected=savedAnswer(index);try{const data=await accountApi({action:"get_answer",player_id:playerId(),question_num:questionNumber(index)});if(data.answered&&data.answer){const letter=String(data.answer.answer||"").trim().toUpperCase(),backendIndex=["A","B","C","D"].indexOf(letter);if(backendIndex>=0)selected=backendIndex}}catch(e){}return Number.isInteger(selected)&&selected>=0&&selected<=3?selected:null}
async function showPreviousQuestionsWeek(weekStart){page(`<div class="loading">Loading previous questions...</div>`);const monday=new Date(weekStart+"T12:00:00"),sunday=historyAddDays(monday,6),last=historyReleasedLastIndex(),rows=[];for(let i=0;i<=last;i++){const d=historyDateForIndex(i);if(d>=historyMonday(monday)&&d<=sunday)rows.push({index:i,date:d,answer:await historyPlayerAnswer(i)})}let htmlRows="";for(const row of rows){const q=questions[row.index];if(!q||!q.question||!Array.isArray(q.answers))continue;const correct=q.correct,your=row.answer,options=q.answers.map((answer,idx)=>`<div style="padding:7px 0"><strong>${String.fromCharCode(65+idx)}/</strong> ${html(answer)}</div>`).join(""),yourText=your===null?"Not answered":`${String.fromCharCode(65+your)}/ ${html(q.answers[your])}`,correctText=`${String.fromCharCode(65+correct)}/ ${html(q.answers[correct])}`;htmlRows+=`<div class="wall-card" style="background:#fff;border:2px solid var(--history);text-align:left"><h3 style="margin-bottom:4px">${html(historyDateLabel(row.date))}</h3><small style="text-align:left;margin-bottom:12px">Question ${questionNumber(row.index)}</small><p><strong>${html(q.question)}</strong></p><div>${options}</div><div class="notice" style="text-align:left"><strong>Your answer:</strong><br>${yourText}</div><div class="notice" style="text-align:left"><strong>Correct answer:</strong><br>${correctText}</div></div>`}if(!htmlRows)htmlRows=`<div class="notice">No released questions are available for this week yet.</div>`;page(`<div class="section history"><h2 class="center">PREVIOUS QUESTIONS</h2><p class="center"><strong>${historyShortDate(monday)} – ${historyShortDate(sunday)}</strong></p>${htmlRows}</div>${back("showPreviousQuestions")}`)}

async function showRankings(){page(`<div class="loading">Loading rankings...</div>`);try{const pref=await accountApi({action:"ranking_preference",player_id:playerId()});if(!pref.decided){showRankingChoice();return}const data=await loadDashboard();renderRankingMenu(data,pref.share_ranking)}catch(e){page(`<div class="section history"><h2 class="center">RANKINGS</h2><div class="notice">The rankings could not be loaded.</div></div>${back("showHistory")}`)}}
function showRankingChoice(){page(`<div class="section history"><h2 class="center">RANKINGS</h2><div class="settings-card center"><h3>Would you like to appear in the rankings?</h3><p>If you choose yes, your player name and quiz statistics can appear in the weekly, monthly and Top 20 rankings.</p><button onclick="setRankingChoice(true)">YES — INCLUDE ME</button><button onclick="setRankingChoice(false)">NO — KEEP MY RESULTS PRIVATE</button><p><small>You can change this later in Personal Settings.</small></p></div></div>${back("showHistory")}`)}
async function setRankingChoice(value){await accountApi({action:"set_ranking_preference",player_id:playerId(),player_name:playerName(),share_ranking:value});dashboardCache=null;showRankings()}
function renderRankingMenu(data,shared){page(`<div class="section history"><h2 class="center">RANKINGS</h2><div class="notice center">Your results are currently <strong>${shared?"VISIBLE":"PRIVATE"}</strong> in rankings.</div><div class="menu"><button onclick="showRankingTable('week')">THIS WEEK</button><button onclick="showRankingTable('month')">THIS MONTH</button><button onclick="showRankingTable('top20')">TOP 20 — ALL TIME</button></div></div>${back("showHistory")}`)}
async function showRankingTable(type){page(`<div class="loading">Loading ranking...</div>`);try{const data=await loadDashboard(),block=type==="week"?data.week:type==="month"?data.month:data.top20,title=type==="week"?"THIS WEEK":type==="month"?"THIS MONTH":"TOP 20 — ALL TIME",rows=Array.isArray(block?.leaderboard)?block.leaderboard:[];let body=rows.map(r=>`<tr><td><strong>#${r.rank}</strong></td><td>${html(r.player_name)}</td><td>${r.correct}</td><td>${r.played}</td><td>${r.accuracy}%</td></tr>`).join("");if(!body)body=`<tr><td colspan="5">No players are sharing ranking results yet.</td></tr>`;page(`<div class="section history"><h2 class="center">${title}</h2><div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;text-align:left"><thead><tr><th>Rank</th><th>Player</th><th>Correct</th><th>Days</th><th>Accuracy</th></tr></thead><tbody>${body}</tbody></table></div></div>${back("showRankings")}`)}catch(e){page(`<div class="section history"><h2 class="center">RANKING</h2><div class="notice">The ranking could not be loaded.</div></div>${back("showRankings")}`)}}

function showWallOfFameMenu(){page(`<div class="section history"><h2 class="center">WALL OF FAME</h2><div class="menu"><button onclick="showWeeklyWallOfFame()" style="border-color:var(--gold);font-weight:bold">SMARTEST BDL'ER OF THE WEEK</button><button onclick="showSupremeWallOfFame()" style="border-color:var(--copper);font-weight:bold">SUPREME BDL'ER</button></div></div>${back("showHistory")}`)}
async function showWeeklyWallOfFame(){page(`<div class="loading">Loading Wall of Fame...</div>`);try{const data=await loadDashboard(),rows=Array.isArray(data?.history?.weekly)?data.history.weekly:[],cards=rows.length?rows.map(row=>`<div class="wall-card week"><strong>SMARTEST BDL'ER OF THE WEEK</strong><h3>${html(row.player_name)}</h3><div>${row.correct_answers??0} correct · ${row.days_played??0} days played</div><small>${html(row.week_start)} — ${html(row.week_end)}</small></div>`).join(""):`<div class="notice">No weekly winners yet.</div>`;page(`<div class="section history"><h2 class="center">SMARTEST BDL'ER OF THE WEEK</h2>${cards}</div>${back("showWallOfFameMenu")}`)}catch(e){page(`<div class="section history"><h2 class="center">SMARTEST BDL'ER OF THE WEEK</h2><div class="notice">The weekly Wall of Fame could not be loaded.</div></div>${back("showWallOfFameMenu")}`)}}
async function showSupremeWallOfFame(){page(`<div class="loading">Loading Wall of Fame...</div>`);try{const data=await loadDashboard(),rows=Array.isArray(data?.history?.monthly)?data.history.monthly:[],cards=rows.length?rows.map(row=>`<div class="wall-card month"><strong>THE SUPREME BDL'ER</strong><h3>${html(row.player_name)}</h3><div>${row.correct_answers??0} correct · ${row.days_played??0} days played</div><small>${html(row.month_start)} — ${html(row.month_end)}</small></div>`).join(""):`<div class="notice">No Supreme BDL'er winners yet.</div>`;page(`<div class="section history"><h2 class="center">SUPREME BDL'ER</h2>${cards}</div>${back("showWallOfFameMenu")}`)}catch(e){page(`<div class="section history"><h2 class="center">SUPREME BDL'ER</h2><div class="notice">The Supreme Wall of Fame could not be loaded.</div></div>${back("showWallOfFameMenu")}`)}}