from pathlib import Path

p = Path('recovery-onboarding.js')
s = p.read_text()
old = '''  const stats=bdlStatsBlock(data,type);\n  const label=type==="week"?"THIS WEEK":type==="month"?"THIS MONTH":"ALL TIME";\n  let titleSection="";\n  if(type==="all"){\n    titleSection=`\n      <h3 class="center" style="margin-top:28px">TITLE TOP 20 — ALL TIME</h3>\n      <div class="title-points-note">Test accounts can view this read-only title ranking for verification.</div>\n      ${bdlRenderTitleTop20(data,"all")}`;\n  }\n  area.innerHTML=`\n    <h3 class="center" style="margin-top:18px">${label}</h3>\n    <div class="stat-grid">\n      <div class="stat-card"><strong>${stats.played}</strong>Played</div>\n      <div class="stat-card"><strong>${stats.correct}</strong>Correct</div>\n      <div class="stat-card"><strong>${stats.incorrect}</strong>Incorrect</div>\n      <div class="stat-card"><strong>${stats.accuracy}%</strong>Accuracy</div>\n    </div>\n    <h3 class="center" style="margin-top:24px">QUIZ TOP 20 — ${label}</h3>\n    ${bdlTestGeneralTop20(data,type)}\n    ${titleSection}\n    <div class="notice"><strong>TEST ACCOUNT</strong><br>This is a read-only admin/test view. Test accounts remain excluded from rankings and winner selection.</div>`;'''
new = '''  const label=type==="week"?"THIS WEEK":type==="month"?"THIS MONTH":"ALL TIME";\n  let titleSection="";\n  if(type==="all"){\n    titleSection=`\n      <h3 class="center" style="margin-top:28px">TITLE TOP 20 — ALL TIME</h3>\n      <div class="title-points-note">Test accounts can view this read-only title ranking for verification.</div>\n      ${bdlRenderTitleTop20(data,"all")}`;\n  }\n  area.innerHTML=`\n    <h3 class="center" style="margin-top:18px">${label}</h3>\n    <div class="notice" style="text-align:left"><strong>READ-ONLY ADMIN VIEW</strong><br>The test account itself is excluded from quiz statistics. The rankings below show the real player data for verification.</div>\n    <h3 class="center" style="margin-top:24px">QUIZ TOP 20 — ${label}</h3>\n    ${bdlTestGeneralTop20(data,type)}\n    ${titleSection}\n    <div class="notice"><strong>TEST ACCOUNT</strong><br>This is a read-only admin/test view. Test accounts remain excluded from statistics, rankings and winner selection.</div>`;'''
if old not in s:
    raise SystemExit('Expected test statistics block not found')
s = s.replace(old, new, 1)
p.write_text(s)
